"""Professional chart styling for matplotlib.

Provides a consistent color palette and styling for charts
generated by the AI Command Bot agents.
"""

import matplotlib
matplotlib.use("Agg")  # Non-interactive backend for server use
import matplotlib.pyplot as plt  # noqa: E402
from pathlib import Path  # noqa: E402

# Professional color palette
COLORS = {
    "primary": "#1a73e8",
    "secondary": "#34a853",
    "accent1": "#ea4335",
    "accent2": "#fbbc04",
    "accent3": "#9334e6",
    "accent4": "#ff6d01",
    "light_bg": "#f8f9ff",
    "grid": "#e8e8e8",
    "text": "#1a1a1a",
    "text_muted": "#666666",
}

PALETTE = [
    COLORS["primary"], COLORS["secondary"], COLORS["accent1"],
    COLORS["accent2"], COLORS["accent3"], COLORS["accent4"],
]

CHART_DIR = Path(__file__).resolve().parent.parent.parent / "outputs" / "charts"


def apply_style() -> None:
    """Apply professional styling to matplotlib."""
    plt.rcParams.update({
        "figure.figsize": (10, 6),
        "figure.dpi": 150,
        "figure.facecolor": "white",
        "axes.facecolor": "white",
        "axes.edgecolor": COLORS["grid"],
        "axes.labelcolor": COLORS["text"],
        "axes.titlesize": 14,
        "axes.titleweight": "bold",
        "axes.labelsize": 11,
        "axes.grid": True,
        "axes.prop_cycle": plt.cycler(color=PALETTE),
        "grid.color": COLORS["grid"],
        "grid.linewidth": 0.5,
        "grid.alpha": 0.7,
        "xtick.color": COLORS["text_muted"],
        "ytick.color": COLORS["text_muted"],
        "xtick.labelsize": 10,
        "ytick.labelsize": 10,
        "font.family": "sans-serif",
        "font.sans-serif": [
            "-apple-system", "BlinkMacSystemFont", "Segoe UI",
            "Roboto", "Helvetica", "Arial", "sans-serif",
        ],
        "legend.fontsize": 10,
        "legend.framealpha": 0.9,
    })


def ensure_chart_dir() -> Path:
    """Create and return the chart output directory."""
    CHART_DIR.mkdir(parents=True, exist_ok=True)
    return CHART_DIR
